version: '2'
services:
  apollo:
    image: docker-apollo:latest
    container_name: apollo
    network_mode: "host"
    restart: always
    ports:
     - "0.0.0.0:8070:8070"
    volumes:
      - /opt/logs:/opt/logs
# 启动前,确认对应环境的数据库已经建立，否则apollo无法启动.
# 默认端口:portal:8070; dev:8080,8090; fat:8081,8091; uat:8082,8092; pro:8083,8093
    environment:
      PORTAL_DB: jdbc:mysql://115.159.108.80:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: standarddb
      PORTAL_DB_PWD: mysql112358
      #PORTAL_PORT: 8170
      #AVA_OPTS: '-Deureka.service.url=http://localhost:8180/eureka/'
#      PORTAL_PORT: 80

      DEV_DB: jdbc:mysql://115.159.108.80:3306/ApolloConfigDB?characterEncoding=utf8
      DEV_DB_USER: standarddb
      DEV_DB_PWD: mysql112358
      #DEV_ADMIN_PORT: 8190
      DEV_CONFIG_PORT: 8080
      
